# 📌 Extracción

## Importación de librerías

In [182]:
import pandas as pd
import matplotlib.pyplot as plt

In [183]:
import requests
import json

## Carga de datos

In [184]:
# Cargar los datos desde la API
origin_dataset_url = "https://raw.githubusercontent.com/alura-cursos/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json"
response = requests.get(origin_dataset_url)
data = json.loads(response.text)

In [185]:
# Verificar que los datos se han cargado correctamente
print(response.status_code)  # Debe ser 200
print(response.text[:500])   # Muestra los primeros 500 caracteres
print(type(data))            # Debe ser dict o list

200
[{"customerID":"0002-ORFBO","Churn":"No","customer":{"gender":"Female","SeniorCitizen":0,"Partner":"Yes","Dependents":"Yes","tenure":9},"phone":{"PhoneService":"Yes","MultipleLines":"No"},"internet":{"InternetService":"DSL","OnlineSecurity":"No","OnlineBackup":"Yes","DeviceProtection":"No","TechSupport":"Yes","StreamingTV":"Yes","StreamingMovies":"No"},"account":{"Contract":"One year","PaperlessBilling":"Yes","PaymentMethod":"Mailed check","Charges":{"Monthly":65.6,"Total":"593.3"}}},{"customerI
<class 'list'>

In [186]:
# Normalizar datos del objeto y traducirlo a un DataFrame de pandas
df  = pd.json_normalize(data)

In [187]:
# Ver df
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

## Funciones reutilizables

In [188]:
def imprimir_generalidades_cols_df(df, col_names):
    for col in col_names:
        print(f'\tNOMBRE DE LA COLUMNA: {col} '
              f'\nTIPO DE DATO: {df[col].dtype} '
              f'\nNÚMERO DE VALORES ÚNICOS: {df[col].nunique()} '
              f'\nVALORES ÚNICOS: {df[col].unique()}'
              f'\nRECUENTO DE CADA VALOR:\n{df[col].value_counts()}\n')

# 🔧 Transformación

## Explorar el conjunto de datos

In [189]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB
None

En esta primera exploración, la columna objetivo es *Churn*. Las demás columnas pueden influir en *Churn*. La mayoría son columnas categóricas, es necesario realizar las transformaciones pertinentes para que el tipo corresponda con lo expresado en el diccionario de datos.
No existen valores nulos.

## Identificación de inconsistencias

In [190]:
# Valores únicos por columna
imprimir_generalidades_cols_df(df, df.columns)

	NOMBRE DE LA COLUMNA: customerID
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 7267
VALORES ÚNICOS: ['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
RECUENTO DE CADA VALOR:
customerID
0002-ORFBO    1
6614-VBEGU    1
6637-KYRCV    1
6635-MYYYZ    1
6635-CPNUN    1
             ..
3374-TTZTK    1
3374-PZLXD    1
3374-LXDEV    1
3373-YZZYM    1
9995-HOTOH    1
Name: count, Length: 7267, dtype: int64

	NOMBRE DE LA COLUMNA: Churn
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['No' 'Yes' '']
RECUENTO DE CADA VALOR:
Churn
No     5174
Yes    1869
        224
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.gender
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: ['Female' 'Male']
RECUENTO DE CADA VALOR:
customer.gender
Male      3675
Female    3592
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.SeniorCitizen
TIPO DE DATO: int64
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [0 1]
RECUENTO DE CADA VALOR:
customer.SeniorCitizen
0    6085
1    1182
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.Partner
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: ['Yes' 'No']
RECUENTO DE CADA VALOR:
customer.Partner
No     3749
Yes    3518
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.Dependents
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: ['Yes' 'No']
RECUENTO DE CADA VALOR:
customer.Dependents
No     5086
Yes    2181
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.tenure
TIPO DE DATO: int64
NÚMERO DE VALORES ÚNICOS: 73
VALORES ÚNICOS: [ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]
RECUENTO DE CADA VALOR:
customer.tenure
1     634
72    369
2     246
3     207
4     185
     ...
38     60
39     59
44     54
36     50
0      11
Name: count, Length: 73, dtype: int64

	NOMBRE DE LA COLUMNA: phone.PhoneService
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: ['Yes' 'No']
RECUENTO DE CADA VALOR:
phone.PhoneService
Yes    6560
No      707
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: phone.MultipleLines
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['No' 'Yes' 'No phone service']
RECUENTO DE CADA VALOR:
phone.MultipleLines
No                  3495
Yes                 3065
No phone service     707
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.InternetService
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['DSL' 'Fiber optic' 'No']
RECUENTO DE CADA VALOR:
internet.InternetService
Fiber optic    3198
DSL            2488
No             1581
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.OnlineSecurity
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['No' 'Yes' 'No internet service']
RECUENTO DE CADA VALOR:
internet.OnlineSecurity
No                     3608
Yes                    2078
No internet service    1581
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.OnlineBackup
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['Yes' 'No' 'No internet service']
RECUENTO DE CADA VALOR:
internet.OnlineBackup
No                     3182
Yes                    2504
No internet service    1581
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.DeviceProtection
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['No' 'Yes' 'No internet service']
RECUENTO DE CADA VALOR:
internet.DeviceProtection
No                     3195
Yes                    2491
No internet service    1581
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.TechSupport
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['Yes' 'No' 'No internet service']
RECUENTO DE CADA VALOR:
internet.TechSupport
No                     3582
Yes                    2104
No internet service    1581
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.StreamingTV
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['Yes' 'No' 'No internet service']
RECUENTO DE CADA VALOR:
internet.StreamingTV
No                     2896
Yes                    2790
No internet service    1581
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.StreamingMovies
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['No' 'Yes' 'No internet service']
RECUENTO DE CADA VALOR:
internet.StreamingMovies
No                     2870
Yes                    2816
No internet service    1581
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.Contract
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['One year' 'Month-to-month' 'Two year']
RECUENTO DE CADA VALOR:
account.Contract
Month-to-month    4005
Two year          1743
One year          1519
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.PaperlessBilling
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: ['Yes' 'No']
RECUENTO DE CADA VALOR:
account.PaperlessBilling
Yes    4311
No     2956
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.PaymentMethod
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 4
VALORES ÚNICOS: ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
RECUENTO DE CADA VALOR:
account.PaymentMethod
Electronic check             2445
Mailed check                 1665
Bank transfer (automatic)    1589
Credit card (automatic)      1568
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.Charges.Monthly
TIPO DE DATO: float64
NÚMERO DE VALORES ÚNICOS: 1585
VALORES ÚNICOS: [65.6  59.9  73.9  ... 91.75 68.8  67.85]
RECUENTO DE CADA VALOR:
account.Charges.Monthly
20.05     65
19.85     46
19.90     46
19.70     45
19.55     45
          ..
23.45      1
116.55     1
106.85     1
68.55      1
67.85      1
Name: count, Length: 1585, dtype: int64

	NOMBRE DE LA COLUMNA: account.Charges.Total
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 6531
VALORES ÚNICOS: ['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']
RECUENTO DE CADA VALOR:
account.Charges.Total
           11
20.2       11
19.75       9
19.55       9
19.9        9
           ..
272         1
1426.45     1
371.6       1
6786.4      1
3707.6      1
Name: count, Length: 6531, dtype: int64

Con estos datos las observaciones más importantes para la identificación de inconsistencias son que todas las IDs de los clientes son únicas y que hay datos sin especificar en la columna *Churn*. Es necesario verificar estas filas que no cuentan con valores en la columna objetivo.

In [191]:
# Identificar filas con valores '' en la columna 'Churn'
churn_empty = df[df['Churn'] == '']
print(churn_empty['customerID'])

30      0047-ZHDTW
75      0120-YZLQA
96      0154-QYHJU
98      0162-RZGMZ
175     0274-VVQOQ
           ...
7158    9840-GSRFX
7180    9872-RZQQB
7211    9920-GNDMB
7239    9955-RVWSC
7247    9966-VYRTZ
Name: customerID, Length: 224, dtype: object

Otra inconsistencia detectada es el tipo de la columna *account.Charges.Total* la cual debería corresponder a un tipo float como *account.Charges.Monthly*

## Manejo de inconsistencias

### Eliminación de filas
Para el propósito de este análisis son de suma importancia los valores de la columna *Churn* por lo que no servirán las filas que no cuentan con la información de que el cliente dejó o no la empresa.

In [192]:
# Eliminar filas con valores '' en la columna 'Churn'
df = df[df['Churn'] != '']

In [193]:
# Verificar eliminación
print(f'Valores de Churn: {df['Churn'].unique()}') # Sin '' en 'Churn'
print(f'Número de filas después de eliminar valores vacíos en Churn: {len(df)}') # Deben de ser 7267 - 224 = 7043 filas

Valores de Churn: ['No' 'Yes']
Número de filas después de eliminar valores vacíos en Churn: 7043

### Cambios de tipo

In [194]:
# Imprimir solo las filas con valores vacíos en 'account.Charges.Total'
print(df.loc[df['account.Charges.Total'] == ' ', ['customerID', 'account.Charges.Total']])

      customerID account.Charges.Total
975   1371-DWPAZ
1775  2520-SGTTA
1955  2775-SEFEE
2075  2923-ARZLG
2232  3115-CZMZD
2308  3213-VVOLG
2930  4075-WKNIU
3134  4367-NUYAO
3203  4472-LVYGI
4169  5709-LVOEQ
5599  7644-OMVMY

pandas no lee como float64 a la columna account.Charges.Total debido a que tiene como valores ' ', por lo que detecta la columna como objeto. De esta forma al hacer la transformación siguiente, esos valores los llenará como NaN.

In [195]:
# Cambiar tipo de objeto a float64 en la columna 'account.Charges.Total'
#df['account.Charges.Total'] = pd.to_numeric(df['account.Charges.Total'], errors='coerce') 
df.loc[:, 'account.Charges.Total'] = pd.to_numeric(df['account.Charges.Total'], errors='coerce') # If 'coerce', then invalid parsing will be set as NaN.

In [196]:
# Verificar cambio de tipo  
print(df.info())  # Debe ser float64
# verificar 11 NaN en 'account.Charges.Total' (valores originales como ' ' convertidos a NaN)
print(f'Número de valores NaN en account.Charges.Total: {df['account.Charges.Total'].isna().sum()}')

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   Churn                      7043 non-null   object
 2   customer.gender            7043 non-null   object
 3   customer.SeniorCitizen     7043 non-null   int64
 4   customer.Partner           7043 non-null   object
 5   customer.Dependents        7043 non-null   object
 6   customer.tenure            7043 non-null   int64
 7   phone.PhoneService         7043 non-null   object
 8   phone.MultipleLines        7043 non-null   object
 9   internet.InternetService   7043 non-null   object
 10  internet.OnlineSecurity    7043 non-null   object
 11  internet.OnlineBackup      7043 non-null   object
 12  internet.DeviceProtection  7043 non-null   object
 13  internet.TechSupport       7043 non-null   object
 14  internet.StreamingTV       7043 non-null   object
 15  internet.StreamingMovies   7043 non-null   object
 16  account.Contract           7043 non-null   object
 17  account.PaperlessBilling   7043 non-null   object
 18  account.PaymentMethod      7043 non-null   object
 19  account.Charges.Monthly    7043 non-null   float64
 20  account.Charges.Total      7032 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB
None
Número de valores NaN en account.Charges.Total: 11

### Columna de cuentas diarias (Opcional)

In [197]:
#df.loc[:, 'Cuentas_Diarias'] = df['account.Charges.Monthly'] / 30
df['Cuentas_Diarias'] = df['account.Charges.Monthly'] / 30

C:\Users\Nelly\AppData\Local\Temp\ipykernel_314528\3284665824.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Cuentas_Diarias'] = df['account.Charges.Monthly'] / 30

In [198]:
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total,Cuentas_Diarias
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,Yes,No,No,One year,No,Mailed check,55.15,742.9,1.838333
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7,2.836667
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6,1.966667

### Otras transformaciones para estandarizar el formato

In [199]:
# Convertir a mayúsculas las columnas de tipo object, excepto 'account.Charges.Total'
for col in df.columns:
    if df[col].dtype == 'object' and col != 'account.Charges.Total':
        df.loc[:, col] = df[col].str.upper()

In [200]:
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total,Cuentas_Diarias
0,0002-ORFBO,NO,FEMALE,0,YES,YES,9,YES,NO,DSL,...,NO,YES,YES,NO,ONE YEAR,YES,MAILED CHECK,65.60,593.3,2.186667
1,0003-MKNFE,NO,MALE,0,NO,NO,9,YES,YES,DSL,...,NO,NO,NO,YES,MONTH-TO-MONTH,NO,MAILED CHECK,59.90,542.4,1.996667
2,0004-TLHLJ,YES,MALE,0,NO,NO,4,YES,NO,FIBER OPTIC,...,YES,NO,NO,NO,MONTH-TO-MONTH,YES,ELECTRONIC CHECK,73.90,280.85,2.463333
3,0011-IGKFF,YES,MALE,1,YES,NO,13,YES,NO,FIBER OPTIC,...,YES,NO,YES,YES,MONTH-TO-MONTH,YES,ELECTRONIC CHECK,98.00,1237.85,3.266667
4,0013-EXCHZ,YES,FEMALE,1,YES,NO,3,YES,NO,FIBER OPTIC,...,NO,YES,YES,NO,MONTH-TO-MONTH,YES,MAILED CHECK,83.90,267.4,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,NO,FEMALE,0,NO,NO,13,YES,NO,DSL,...,NO,YES,NO,NO,ONE YEAR,NO,MAILED CHECK,55.15,742.9,1.838333
7263,9992-RRAMN,YES,MALE,0,YES,NO,22,YES,YES,FIBER OPTIC,...,NO,NO,NO,YES,MONTH-TO-MONTH,YES,ELECTRONIC CHECK,85.10,1873.7,2.836667
7264,9992-UJOEL,NO,MALE,0,NO,NO,2,YES,NO,DSL,...,NO,NO,NO,NO,MONTH-TO-MONTH,YES,MAILED CHECK,50.30,92.75,1.676667
7265,9993-LHIEB,NO,MALE,0,YES,YES,67,YES,NO,DSL,...,YES,YES,NO,YES,TWO YEAR,NO,MAILED CHECK,67.85,4627.65,2.261667
7266,9995-HOTOH,NO,MALE,0,YES,YES,63,NO,NO PHONE SERVICE,DSL,...,YES,NO,YES,YES,TWO YEAR,NO,ELECTRONIC CHECK,59.00,3707.6,1.966667

## Estandarización y transformación de datos (opcional)

In [201]:
df_transformed = df.copy() # Copia del DataFrame original para transformaciones adicionales

In [202]:
df_transformed.drop(columns=['customerID'], inplace=True) # Eliminar columna 'customerID' por ser un identificador único sin valor predictivo

### Convertir columnas estándar YES/NO a 1/0

In [203]:
dict_yes_no = {'YES': 1, 'NO': 0}
# Nombres de columnas que cuentan con valores 'YES'/'NO' para mapear a 1/0 de manera sencilla
yes_no_col_names = ['Churn', 
                    'customer.Partner', 
                    'customer.Dependents', 
                    #'internet.OnlineSecurity',
                    #'internet.OnlineBackup',
                    #'internet.DeviceProtection',
                    #'internet.TechSupport',
                    #'internet.StreamingTV',
                    #'internet.StreamingMovies',
                    'account.PaperlessBilling']

In [204]:
# Convertir valores 'YES'/'NO' a 1/0 en las columnas correspondientes
for name_col in yes_no_col_names:
    df_transformed.loc[:, name_col] = df_transformed[name_col].map(dict_yes_no)

In [205]:
# Verificar dominio de valores en las columnas transformadas
imprimir_generalidades_cols_df(df, yes_no_col_names)

	NOMBRE DE LA COLUMNA: Churn
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: ['NO' 'YES']
RECUENTO DE CADA VALOR:
Churn
NO     5174
YES    1869
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.Partner
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: ['YES' 'NO']
RECUENTO DE CADA VALOR:
customer.Partner
NO     3641
YES    3402
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.Dependents
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: ['YES' 'NO']
RECUENTO DE CADA VALOR:
customer.Dependents
NO     4933
YES    2110
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.PaperlessBilling
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: ['YES' 'NO']
RECUENTO DE CADA VALOR:
account.PaperlessBilling
YES    4171
NO     2872
Name: count, dtype: int64

### Tratamiento columnas especiales

In [206]:
df_transformed['customer.gender'] = df_transformed['customer.gender'].map({'FEMALE': 0, 'MALE': 1}) # cambiar a es_hombre

### account.Contract

Transformar con one-hot encoding

In [208]:
dummies_account_Contract = pd.get_dummies(df_transformed['account.Contract'], prefix='account.Contract')

In [209]:
dummies_account_Contract

,account.Contract_MONTH-TO-MONTH,account.Contract_ONE YEAR,account.Contract_TWO YEAR
0,False,True,False
1,True,False,False
2,True,False,False
3,True,False,False
4,True,False,False
...,...,...,...
7262,False,True,False
7263,True,False,False
7264,True,False,False
7265,False,False,True
7266,False,False,True

In [210]:
# Unir transformacion con el dataframe
df_transformed = pd.concat([df_transformed, dummies_account_Contract], axis='columns')

In [211]:
# Eliminar columna original
df_transformed.drop(columns='account.Contract', inplace=True)

In [212]:
df_transformed

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,...,internet.StreamingTV,internet.StreamingMovies,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total,Cuentas_Diarias,account.Contract_MONTH-TO-MONTH,account.Contract_ONE YEAR,account.Contract_TWO YEAR
0,0,0,0,1,1,9,YES,NO,DSL,NO,...,YES,NO,1,MAILED CHECK,65.60,593.3,2.186667,False,True,False
1,0,1,0,0,0,9,YES,YES,DSL,NO,...,NO,YES,0,MAILED CHECK,59.90,542.4,1.996667,True,False,False
2,1,1,0,0,0,4,YES,NO,FIBER OPTIC,NO,...,NO,NO,1,ELECTRONIC CHECK,73.90,280.85,2.463333,True,False,False
3,1,1,1,1,0,13,YES,NO,FIBER OPTIC,NO,...,YES,YES,1,ELECTRONIC CHECK,98.00,1237.85,3.266667,True,False,False
4,1,0,1,1,0,3,YES,NO,FIBER OPTIC,NO,...,YES,NO,1,MAILED CHECK,83.90,267.4,2.796667,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,0,0,0,0,0,13,YES,NO,DSL,YES,...,NO,NO,0,MAILED CHECK,55.15,742.9,1.838333,False,True,False
7263,1,1,0,1,0,22,YES,YES,FIBER OPTIC,NO,...,NO,YES,1,ELECTRONIC CHECK,85.10,1873.7,2.836667,True,False,False
7264,0,1,0,0,0,2,YES,NO,DSL,NO,...,NO,NO,1,MAILED CHECK,50.30,92.75,1.676667,True,False,False
7265,0,1,0,1,1,67,YES,NO,DSL,YES,...,NO,YES,0,MAILED CHECK,67.85,4627.65,2.261667,False,False,True
7266,0,1,0,1,1,63,NO,NO PHONE SERVICE,DSL,YES,...,YES,YES,0,ELECTRONIC CHECK,59.00,3707.6,1.966667,False,False,True

### account.PaymentMethod

One-hot encoding y nueva columna para saber si es un pago automático

In [213]:
dummies_account_PaymentMethod = pd.get_dummies(df_transformed['account.PaymentMethod'], prefix='account.PaymentMethod')

In [214]:
# Nueva columna
dummies_account_PaymentMethod['es_pago_automatico'] = (
    dummies_account_PaymentMethod['account.PaymentMethod_BANK TRANSFER (AUTOMATIC)'] |
    dummies_account_PaymentMethod['account.PaymentMethod_CREDIT CARD (AUTOMATIC)']
)

In [215]:
dummies_account_PaymentMethod

,account.PaymentMethod_BANK TRANSFER (AUTOMATIC),account.PaymentMethod_CREDIT CARD (AUTOMATIC),account.PaymentMethod_ELECTRONIC CHECK,account.PaymentMethod_MAILED CHECK,es_pago_automatico
0,False,False,False,True,False
1,False,False,False,True,False
2,False,False,True,False,False
3,False,False,True,False,False
4,False,False,False,True,False
...,...,...,...,...,...
7262,False,False,False,True,False
7263,False,False,True,False,False
7264,False,False,False,True,False
7265,False,False,False,True,False
7266,False,False,True,False,False

In [216]:
# eliminar col original
df_transformed.drop(columns='account.PaymentMethod', inplace=True)

In [217]:
# Unir transformacion con el dataframe
df_transformed = pd.concat([df_transformed, dummies_account_PaymentMethod], axis='columns')

In [218]:
df_transformed

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,...,account.Charges.Total,Cuentas_Diarias,account.Contract_MONTH-TO-MONTH,account.Contract_ONE YEAR,account.Contract_TWO YEAR,account.PaymentMethod_BANK TRANSFER (AUTOMATIC),account.PaymentMethod_CREDIT CARD (AUTOMATIC),account.PaymentMethod_ELECTRONIC CHECK,account.PaymentMethod_MAILED CHECK,es_pago_automatico
0,0,0,0,1,1,9,YES,NO,DSL,NO,...,593.3,2.186667,False,True,False,False,False,False,True,False
1,0,1,0,0,0,9,YES,YES,DSL,NO,...,542.4,1.996667,True,False,False,False,False,False,True,False
2,1,1,0,0,0,4,YES,NO,FIBER OPTIC,NO,...,280.85,2.463333,True,False,False,False,False,True,False,False
3,1,1,1,1,0,13,YES,NO,FIBER OPTIC,NO,...,1237.85,3.266667,True,False,False,False,False,True,False,False
4,1,0,1,1,0,3,YES,NO,FIBER OPTIC,NO,...,267.4,2.796667,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,0,0,0,0,0,13,YES,NO,DSL,YES,...,742.9,1.838333,False,True,False,False,False,False,True,False
7263,1,1,0,1,0,22,YES,YES,FIBER OPTIC,NO,...,1873.7,2.836667,True,False,False,False,False,True,False,False
7264,0,1,0,0,0,2,YES,NO,DSL,NO,...,92.75,1.676667,True,False,False,False,False,False,True,False
7265,0,1,0,1,1,67,YES,NO,DSL,YES,...,4627.65,2.261667,False,False,True,False,False,False,True,False
7266,0,1,0,1,1,63,NO,NO PHONE SERVICE,DSL,YES,...,3707.6,1.966667,False,False,True,False,False,True,False,False

### Líneas de teléfono

En lugar de las columnas phone.PhoneService y phone.MultipleLines se reemplazan por tiene_mas_de_1_linea_tel y tiene_1_linea_tel, siendo que los clientes sin línea tendrán valores de FALSE o 0 en ambas cols

In [219]:
dummies_phoneMultipleLines = pd.get_dummies(df_transformed['phone.MultipleLines'], prefix='phone_')

In [220]:
dummies_phoneMultipleLines

      phone__NO  phone__NO PHONE SERVICE  phone__YES
0          True                    False       False
1         False                    False        True
2          True                    False       False
3          True                    False       False
4          True                    False       False
...         ...                      ...         ...
7262       True                    False       False
7263      False                    False        True
7264       True                    False       False
7265       True                    False       False
7266      False                     True       False

[7043 rows x 3 columns]

In [221]:
df_transformed = pd.concat([df_transformed, dummies_phoneMultipleLines], axis='columns')

In [222]:
df_transformed.drop(columns=['phone.PhoneService', 'phone.MultipleLines'], inplace=True)

In [223]:
df_transformed

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,internet.InternetService,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,...,account.Contract_ONE YEAR,account.Contract_TWO YEAR,account.PaymentMethod_BANK TRANSFER (AUTOMATIC),account.PaymentMethod_CREDIT CARD (AUTOMATIC),account.PaymentMethod_ELECTRONIC CHECK,account.PaymentMethod_MAILED CHECK,es_pago_automatico,phone__NO,phone__NO PHONE SERVICE,phone__YES
0,0,0,0,1,1,9,DSL,NO,YES,NO,...,True,False,False,False,False,True,False,True,False,False
1,0,1,0,0,0,9,DSL,NO,NO,NO,...,False,False,False,False,False,True,False,False,False,True
2,1,1,0,0,0,4,FIBER OPTIC,NO,NO,YES,...,False,False,False,False,True,False,False,True,False,False
3,1,1,1,1,0,13,FIBER OPTIC,NO,YES,YES,...,False,False,False,False,True,False,False,True,False,False
4,1,0,1,1,0,3,FIBER OPTIC,NO,NO,NO,...,False,False,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,0,0,0,0,0,13,DSL,YES,NO,NO,...,True,False,False,False,False,True,False,True,False,False
7263,1,1,0,1,0,22,FIBER OPTIC,NO,NO,NO,...,False,False,False,False,True,False,False,False,False,True
7264,0,1,0,0,0,2,DSL,NO,YES,NO,...,False,False,False,False,False,True,False,True,False,False
7265,0,1,0,1,1,67,DSL,YES,NO,YES,...,False,True,False,False,False,True,False,True,False,False
7266,0,1,0,1,1,63,DSL,YES,YES,YES,...,False,True,False,False,True,False,False,False,True,False

### tiene_serv_internet

Todas las columnas relacionadas a internet y nuevas

In [224]:
# Verificar que todas las columnas que comienzan con internet coincidan en mencionar a los clientes sin servicio de internet
#imprimir_generalidades_cols_df(df_transformed, df_transformed.columns)
imprimir_generalidades_cols_df(df_transformed, [col for col in df_transformed.columns if col.startswith("internet.")])

	NOMBRE DE LA COLUMNA: internet.InternetService
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['DSL' 'FIBER OPTIC' 'NO']
RECUENTO DE CADA VALOR:
internet.InternetService
FIBER OPTIC    3096
DSL            2421
NO             1526
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.OnlineSecurity
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['NO' 'YES' 'NO INTERNET SERVICE']
RECUENTO DE CADA VALOR:
internet.OnlineSecurity
NO                     3498
YES                    2019
NO INTERNET SERVICE    1526
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.OnlineBackup
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['YES' 'NO' 'NO INTERNET SERVICE']
RECUENTO DE CADA VALOR:
internet.OnlineBackup
NO                     3088
YES                    2429
NO INTERNET SERVICE    1526
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.DeviceProtection
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['NO' 'YES' 'NO INTERNET SERVICE']
RECUENTO DE CADA VALOR:
internet.DeviceProtection
NO                     3095
YES                    2422
NO INTERNET SERVICE    1526
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.TechSupport
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['YES' 'NO' 'NO INTERNET SERVICE']
RECUENTO DE CADA VALOR:
internet.TechSupport
NO                     3473
YES                    2044
NO INTERNET SERVICE    1526
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.StreamingTV
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['YES' 'NO' 'NO INTERNET SERVICE']
RECUENTO DE CADA VALOR:
internet.StreamingTV
NO                     2810
YES                    2707
NO INTERNET SERVICE    1526
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.StreamingMovies
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 3
VALORES ÚNICOS: ['NO' 'YES' 'NO INTERNET SERVICE']
RECUENTO DE CADA VALOR:
internet.StreamingMovies
NO                     2785
YES                    2732
NO INTERNET SERVICE    1526
Name: count, dtype: int64

Todos los valores que indican que no se cuenta con servicio de internet coinciden a través de todas las columnas referentes por lo que es posible usar cualquier columna para crear tiene_serv_internet

In [226]:
# Crear columna tiene_serv_internet
df_transformed['tiene_serv_internet'] = df_transformed['internet.InternetService'].apply(lambda x: True if x == 'NO' else False)

In [233]:
# Aplicar en las otras columnas de internet la conversión a binario
for col_internet in df_transformed.columns:
    if col_internet.startswith("internet.") and col_internet != 'internet.InternetService':
        df_transformed[col_internet] = df_transformed[col_internet].apply(lambda x: True if x == 'YES' else False)
        print(f'Columna {col_internet} cambiada')

Columna internet.OnlineSecurity cambiada
Columna internet.OnlineBackup cambiada
Columna internet.DeviceProtection cambiada
Columna internet.TechSupport cambiada
Columna internet.StreamingTV cambiada
Columna internet.StreamingMovies cambiada

In [228]:
# Eliminar la columna original internet.InternetService
df_transformed.drop(columns='internet.InternetService', inplace=True)

Si las nuevas columnas es_internet_dsl False o 0 y a parte tiene_serv_internet en True o 1, entonces el servicio de internet del cliente es de fibra óptica

In [234]:
df_transformed

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,...,account.Contract_TWO YEAR,account.PaymentMethod_BANK TRANSFER (AUTOMATIC),account.PaymentMethod_CREDIT CARD (AUTOMATIC),account.PaymentMethod_ELECTRONIC CHECK,account.PaymentMethod_MAILED CHECK,es_pago_automatico,phone__NO,phone__NO PHONE SERVICE,phone__YES,tiene_serv_internet
0,0,0,0,1,1,9,False,True,False,True,...,False,False,False,False,True,False,True,False,False,False
1,0,1,0,0,0,9,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
2,1,1,0,0,0,4,False,False,True,False,...,False,False,False,True,False,False,True,False,False,False
3,1,1,1,1,0,13,False,True,True,False,...,False,False,False,True,False,False,True,False,False,False
4,1,0,1,1,0,3,False,False,False,True,...,False,False,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,0,0,0,0,0,13,True,False,False,True,...,False,False,False,False,True,False,True,False,False,False
7263,1,1,0,1,0,22,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
7264,0,1,0,0,0,2,False,True,False,False,...,False,False,False,False,True,False,True,False,False,False
7265,0,1,0,1,1,67,True,False,True,True,...,True,False,False,False,True,False,True,False,False,False
7266,0,1,0,1,1,63,True,True,True,False,...,True,False,False,True,False,False,False,True,False,False

In [235]:
# Verificar transformaciones
imprimir_generalidades_cols_df(df_transformed, df_transformed.columns)

	NOMBRE DE LA COLUMNA: Churn
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [0 1]
RECUENTO DE CADA VALOR:
Churn
0    5174
1    1869
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.gender
TIPO DE DATO: int64
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [0 1]
RECUENTO DE CADA VALOR:
customer.gender
1    3555
0    3488
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.SeniorCitizen
TIPO DE DATO: int64
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [0 1]
RECUENTO DE CADA VALOR:
customer.SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.Partner
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [1 0]
RECUENTO DE CADA VALOR:
customer.Partner
0    3641
1    3402
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.Dependents
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [1 0]
RECUENTO DE CADA VALOR:
customer.Dependents
0    4933
1    2110
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: customer.tenure
TIPO DE DATO: int64
NÚMERO DE VALORES ÚNICOS: 73
VALORES ÚNICOS: [ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 37 49 66 67
 20 43 59 12 27  2 25 29 14 35 64 39 40 11  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 31 36 17 18 51 38 42
  0]
RECUENTO DE CADA VALOR:
customer.tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

	NOMBRE DE LA COLUMNA: internet.OnlineSecurity
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
internet.OnlineSecurity
False    5024
True     2019
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.OnlineBackup
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [ True False]
RECUENTO DE CADA VALOR:
internet.OnlineBackup
False    4614
True     2429
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.DeviceProtection
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
internet.DeviceProtection
False    4621
True     2422
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.TechSupport
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [ True False]
RECUENTO DE CADA VALOR:
internet.TechSupport
False    4999
True     2044
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.StreamingTV
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [ True False]
RECUENTO DE CADA VALOR:
internet.StreamingTV
False    4336
True     2707
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: internet.StreamingMovies
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
internet.StreamingMovies
False    4311
True     2732
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.PaperlessBilling
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [1 0]
RECUENTO DE CADA VALOR:
account.PaperlessBilling
1    4171
0    2872
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.Charges.Monthly
TIPO DE DATO: float64
NÚMERO DE VALORES ÚNICOS: 1585
VALORES ÚNICOS: [65.6  59.9  73.9  ... 91.75 68.8  67.85]
RECUENTO DE CADA VALOR:
account.Charges.Monthly
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
116.55     1
106.85     1
68.55      1
108.80     1
67.85      1
Name: count, Length: 1585, dtype: int64

	NOMBRE DE LA COLUMNA: account.Charges.Total
TIPO DE DATO: object
NÚMERO DE VALORES ÚNICOS: 6530
VALORES ÚNICOS: [593.3 542.4 280.85 ... 742.9 4627.65 3707.6]
RECUENTO DE CADA VALOR:
account.Charges.Total
20.20      11
19.75       9
19.90       8
19.65       8
20.05       8
           ..
2387.75     1
6302.80     1
2058.50     1
829.55      1
3707.60     1
Name: count, Length: 6530, dtype: int64

	NOMBRE DE LA COLUMNA: Cuentas_Diarias
TIPO DE DATO: float64
NÚMERO DE VALORES ÚNICOS: 1585
VALORES ÚNICOS: [2.18666667 1.99666667 2.46333333 ... 3.05833333 2.29333333 2.26166667]
RECUENTO DE CADA VALOR:
Cuentas_Diarias
0.668333    61
0.661667    45
0.665000    44
0.663333    44
0.666667    43
            ..
3.885000     1
3.561667     1
2.285000     1
3.626667     1
2.261667     1
Name: count, Length: 1585, dtype: int64

	NOMBRE DE LA COLUMNA: account.Contract_MONTH-TO-MONTH
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
account.Contract_MONTH-TO-MONTH
True     3875
False    3168
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.Contract_ONE YEAR
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [ True False]
RECUENTO DE CADA VALOR:
account.Contract_ONE YEAR
False    5570
True     1473
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.Contract_TWO YEAR
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
account.Contract_TWO YEAR
False    5348
True     1695
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.PaymentMethod_BANK TRANSFER (AUTOMATIC)
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
account.PaymentMethod_BANK TRANSFER (AUTOMATIC)
False    5499
True     1544
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.PaymentMethod_CREDIT CARD (AUTOMATIC)
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
account.PaymentMethod_CREDIT CARD (AUTOMATIC)
False    5521
True     1522
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.PaymentMethod_ELECTRONIC CHECK
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
account.PaymentMethod_ELECTRONIC CHECK
False    4678
True     2365
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: account.PaymentMethod_MAILED CHECK
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [ True False]
RECUENTO DE CADA VALOR:
account.PaymentMethod_MAILED CHECK
False    5431
True     1612
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: es_pago_automatico
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
es_pago_automatico
False    3977
True     3066
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: phone__NO
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [ True False]
RECUENTO DE CADA VALOR:
phone__NO
False    3653
True     3390
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: phone__NO PHONE SERVICE
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
phone__NO PHONE SERVICE
False    6361
True      682
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: phone__YES
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
phone__YES
False    4072
True     2971
Name: count, dtype: int64

	NOMBRE DE LA COLUMNA: tiene_serv_internet
TIPO DE DATO: bool
NÚMERO DE VALORES ÚNICOS: 2
VALORES ÚNICOS: [False  True]
RECUENTO DE CADA VALOR:
tiene_serv_internet
False    5517
True     1526
Name: count, dtype: int64

# 📊 Carga y análisis

#📄Informe final