# Preparación de los datos
## Librerías y configuraciones

In [17]:
import pandas as pd
import numpy as np
# graficos
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn
import plotly.express as px

In [18]:
from imblearn.under_sampling import RandomUnderSampler # Balanceo de clases por undersampling

In [19]:
# configuración formateo
pd.options.display.max_columns = None
pd.options.display.max_colwidth = 100
pd.options.display.width = 1000

#pd.reset_option('display.max_columns')
pd.reset_option('display.max_colwidth')
pd.reset_option('display.width')

pd.set_option('display.expand_frame_repr', False)

## Extracción del archivo tratado

In [20]:
data_src_path = './TelecomX_Data_prepared.csv'
df = pd.read_csv(data_src_path)

In [21]:
df

      CHURN  ES_HOMBRE  ES_MAYOROIGUAL_65ANIOS  TIENE_PAREJA  TIENE_DEPENDIENTES  NUM_MESES_CONTRATO  TIENE_SEGURIDAD_ENLINEA  TIENE_RESPALDO_ENLINEA  TIENE_PROTECCION_DISPOSITIVO  TIENE_SOPORTE_TECNICO_MAYOR  TIENE_TV_CABLE  TIENE_STREAM_PELIS  ES_FACTURA_ENLINEA  TOTAL_SERV_MES_DOLARES  TOTAL_GASTADO_DOLARES  TOTAL_SERV_MESXDIA_DOLARES  ES_CONTRATO_XMES  ES_CONTRATO_XANIO  ES_CONTRATO_X2ANIOS  ES_PAGO_TRANSF_BANCARIA  ES_PAGO_TARJ_CRED  ES_PAGO_ELECTRONICO  ES_PAGO_POR_CORREO  ES_PAGO_AUTOMATICO  TIENE_1_LIN_TEL  TIENE_MASDE_1_LIN_TEL  TIENE_SERV_INTERNET  TIENE_INTERNET_DSL
0     False      False                   False          True                True                   9                    False                    True                         False                         True            True               False                True                   65.60                 593.30                    2.186667             False               True                False                    False              False                False                True               False             True                  False                 True                True
1     False       True                   False         False               False                   9                    False                   False                         False                        False           False                True               False                   59.90                 542.40                    1.996667              True              False                False                    False              False                False                True               False            False                   True                 True                True
2      True       True                   False         False               False                   4                    False                   False                          True                        False           False               False                True                   73.90                 280.85                    2.463333              True              False                False                    False              False                 True               False               False             True                  False                 True               False
3      True       True                    True          True               False                  13                    False                    True                          True                        False            True                True                True                   98.00                1237.85                    3.266667              True              False                False                    False              False                 True               False               False             True                  False                 True               False
4      True      False                    True          True               False                   3                    False                   False                         False                         True            True               False                True                   83.90                 267.40                    2.796667              True              False                False                    False              False                False                True               False             True                  False                 True               False
...     ...        ...                     ...           ...                 ...                 ...                      ...                     ...                           ...                          ...             ...                 ...                 ...                     ...                    ...                         ...               ...                ...                  ...                      ...                ...                  ...                 ...                 ...              ...                    ...                  ...                 ...
7038  False      False                   False         False               False                  13                     True                   False                         False                         True           False               False               False                   55.15                 742.90                    1.838333             False               True                False                    False              False                False                True               False             True                  False                 True                True
7039   True       True                   False          True               False                  22                    False                   False                         False                        False           False                True                True                   85.10                1873.70                    2.836667              True              False                False                    False              False                 True               False               False            False                   True                 True               False
7040  False       True                   False         False               False                   2                    False                    True                         False                        False           False               False                True                   50.30                  92.75                    1.676667              True              False                False                    False              False                False                True               False             True                  False                 True                True
7041  False       True                   False          True                True                  67                     True                   False                          True                         True           False                True               False                   67.85                4627.65                    2.261667             False              False                 True                    False              False                False                True               False             True                  False                 True                True
7042  False       True                   False          True                True                  63                     True                    True                          True                        False            True                True               False                   59.00                3707.60                    1.966667             False              False                 True                    False              False                 True               False               False            False                  False                 True                True

[7043 rows x 28 columns]

## Eliminación de Columnas Irrelevantes
Esto ya se realizó en la fase uno ([Notebook explicado a detalle](TelecomX_LATAM.ipynb)), siendo que la primera columna irrelevante y eliminada fue `customerID`. Sin embargo, la columna de 'TOTAL_SERV_MESXDIA_DOLARES' ('CuentasDiarias'), es irrelevante por presentar la misma información que 'account.Charges.Monthly' o 'TOTAL_SERV_MES_DOLARES' por lo que se eliminará y creará una columna más relevante 'TOTAL_GASTADOXMES_DOLARES'.

In [22]:
df.drop(columns='TOTAL_SERV_MESXDIA_DOLARES', inplace=True)

In [23]:
df['TOTAL_GASTADOXMES_DOLARES'] = df['TOTAL_GASTADO_DOLARES'] / df['NUM_MESES_CONTRATO']

In [24]:
df

      CHURN  ES_HOMBRE  ES_MAYOROIGUAL_65ANIOS  TIENE_PAREJA  TIENE_DEPENDIENTES  NUM_MESES_CONTRATO  TIENE_SEGURIDAD_ENLINEA  TIENE_RESPALDO_ENLINEA  TIENE_PROTECCION_DISPOSITIVO  TIENE_SOPORTE_TECNICO_MAYOR  TIENE_TV_CABLE  TIENE_STREAM_PELIS  ES_FACTURA_ENLINEA  TOTAL_SERV_MES_DOLARES  TOTAL_GASTADO_DOLARES  ES_CONTRATO_XMES  ES_CONTRATO_XANIO  ES_CONTRATO_X2ANIOS  ES_PAGO_TRANSF_BANCARIA  ES_PAGO_TARJ_CRED  ES_PAGO_ELECTRONICO  ES_PAGO_POR_CORREO  ES_PAGO_AUTOMATICO  TIENE_1_LIN_TEL  TIENE_MASDE_1_LIN_TEL  TIENE_SERV_INTERNET  TIENE_INTERNET_DSL  TOTAL_GASTADOXMES_DOLARES
0     False      False                   False          True                True                   9                    False                    True                         False                         True            True               False                True                   65.60                 593.30             False               True                False                    False              False                False                True               False             True                  False                 True                True                  65.922222
1     False       True                   False         False               False                   9                    False                   False                         False                        False           False                True               False                   59.90                 542.40              True              False                False                    False              False                False                True               False            False                   True                 True                True                  60.266667
2      True       True                   False         False               False                   4                    False                   False                          True                        False           False               False                True                   73.90                 280.85              True              False                False                    False              False                 True               False               False             True                  False                 True               False                  70.212500
3      True       True                    True          True               False                  13                    False                    True                          True                        False            True                True                True                   98.00                1237.85              True              False                False                    False              False                 True               False               False             True                  False                 True               False                  95.219231
4      True      False                    True          True               False                   3                    False                   False                         False                         True            True               False                True                   83.90                 267.40              True              False                False                    False              False                False                True               False             True                  False                 True               False                  89.133333
...     ...        ...                     ...           ...                 ...                 ...                      ...                     ...                           ...                          ...             ...                 ...                 ...                     ...                    ...               ...                ...                  ...                      ...                ...                  ...                 ...                 ...              ...                    ...                  ...                 ...                        ...
7038  False      False                   False         False               False                  13                     True                   False                         False                         True           False               False               False                   55.15                 742.90             False               True                False                    False              False                False                True               False             True                  False                 True                True                  57.146154
7039   True       True                   False          True               False                  22                    False                   False                         False                        False           False                True                True                   85.10                1873.70              True              False                False                    False              False                 True               False               False            False                   True                 True               False                  85.168182
7040  False       True                   False         False               False                   2                    False                    True                         False                        False           False               False                True                   50.30                  92.75              True              False                False                    False              False                False                True               False             True                  False                 True                True                  46.375000
7041  False       True                   False          True                True                  67                     True                   False                          True                         True           False                True               False                   67.85                4627.65             False              False                 True                    False              False                False                True               False             True                  False                 True                True                  69.069403
7042  False       True                   False          True                True                  63                     True                    True                          True                        False            True                True               False                   59.00                3707.60             False              False                 True                    False              False                 True               False               False            False                  False                 True                True                  58.850794

[7043 rows x 28 columns]

## Encoding
Esto ya se realizó en la fase uno ([Notebook explicado a detalle](TelecomX_LATAM.ipynb)).
## Verificación de la Proporción de Cancelación (Churn)
Desde la fase anterior se verificó que hay desbalance de clases, incluso en la variable objetivo de 'CHURN'

In [25]:
print(df.value_counts('CHURN'))

CHURN
False    5174
True     1869
Name: count, dtype: int64

## Balanceo de clases
Se aplica undersampling a la clase mayoritaria (False) para que ambas clases tengan números de registros iguales o similares.

In [26]:
# Configurar el rus
rus = RandomUnderSampler(random_state=0)

In [27]:
df_resampled, y_resampled = rus.fit_resample(df, df['CHURN'])

### Mostrar resultados

In [28]:
df_resampled

      CHURN  ES_HOMBRE  ES_MAYOROIGUAL_65ANIOS  TIENE_PAREJA  TIENE_DEPENDIENTES  NUM_MESES_CONTRATO  TIENE_SEGURIDAD_ENLINEA  TIENE_RESPALDO_ENLINEA  TIENE_PROTECCION_DISPOSITIVO  TIENE_SOPORTE_TECNICO_MAYOR  TIENE_TV_CABLE  TIENE_STREAM_PELIS  ES_FACTURA_ENLINEA  TOTAL_SERV_MES_DOLARES  TOTAL_GASTADO_DOLARES  ES_CONTRATO_XMES  ES_CONTRATO_XANIO  ES_CONTRATO_X2ANIOS  ES_PAGO_TRANSF_BANCARIA  ES_PAGO_TARJ_CRED  ES_PAGO_ELECTRONICO  ES_PAGO_POR_CORREO  ES_PAGO_AUTOMATICO  TIENE_1_LIN_TEL  TIENE_MASDE_1_LIN_TEL  TIENE_SERV_INTERNET  TIENE_INTERNET_DSL  TOTAL_GASTADOXMES_DOLARES
366   False      False                   False          True               False                  28                    False                   False                         False                        False           False               False               False                   20.50                 563.05              True              False                False                    False              False                False                True               False             True                  False                False               False                  20.108929
3031  False      False                   False         False               False                  62                    False                   False                         False                        False           False               False                True                   25.80                1563.95             False              False                 True                    False               True                False               False                True            False                   True                False               False                  25.225000
20    False      False                    True          True               False                  50                    False                   False                         False                        False           False               False               False                   25.20                1306.30             False               True                False                    False              False                 True               False               False            False                   True                False               False                  26.126000
4192  False       True                   False         False               False                   2                    False                   False                         False                        False           False               False               False                   20.05                  42.70              True              False                False                    False              False                False                True               False             True                  False                False               False                  21.350000
189   False      False                   False         False                True                  11                     True                   False                         False                         True           False               False                True                   36.05                 402.60             False               True                False                    False              False                False                True               False            False                  False                 True                True                  36.600000
...     ...        ...                     ...           ...                 ...                 ...                      ...                     ...                           ...                          ...             ...                 ...                 ...                     ...                    ...               ...                ...                  ...                      ...                ...                  ...                 ...                 ...              ...                    ...                  ...                 ...                        ...
7020   True       True                    True         False               False                  21                    False                   False                          True                        False            True                True                True                   96.80                2030.30              True              False                False                     True              False                False               False                True             True                  False                 True               False                  96.680952
7023   True       True                    True         False               False                   9                    False                   False                         False                        False           False                True                True                   83.85                 790.15              True              False                False                    False              False                 True               False               False            False                   True                 True               False                  87.794444
7036   True      False                   False         False               False                   1                    False                   False                         False                        False           False               False                True                   70.15                  70.15              True              False                False                    False              False                False                True               False             True                  False                 True               False                  70.150000
7037   True      False                   False         False               False                   4                    False                   False                         False                        False           False               False               False                   20.95                  85.50              True              False                False                     True              False                False               False                True             True                  False                False               False                  21.375000
7039   True       True                   False          True               False                  22                    False                   False                         False                        False           False                True                True                   85.10                1873.70              True              False                False                    False              False                 True               False               False            False                   True                 True               False                  85.168182

[3738 rows x 28 columns]

In [29]:
y_resampled

366     False
3031    False
20      False
4192    False
189     False
        ...
7020     True
7023     True
7036     True
7037     True
7039     True
Name: CHURN, Length: 3738, dtype: bool

In [30]:
print(df_resampled.value_counts('CHURN'))

CHURN
False    1869
True     1869
Name: count, dtype: int64

## Normalización o Estandarización 
Ya se realizó en la fase anterior.
# Corrección y Selección de variables
## Análisis de correlación